 Containerfile to build an Apache web server image for a website template.

FROM amazonlinux:latest

RUN yum install -y httpd zip unzip && yum clean all

WORKDIR /var/www/html

ADD https://templated.live/snapshot/download/snapshot.zip
RUN unzip /tmp/snapshot.zip -d /var/www/html && rm -f /tmp/snapshot.zip

EXPOSE 81

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
